jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-1-1
        
  - name: runSh-job
    type: runSh
    steps:
      - IN: gitRepo-resource
      - IN: rituraj-1-1
      - TASK:
        - script: echo 'start runSh hello'
        - script: printenv
        
