jobs:
  - name: tri-man
    type: manifest
    steps:
      - GET: tri-sn
      - GET: trigger-dv-man

  - name: tri-man-2
    type: manifest
    steps:
      - GET: tri-nginx
      - GET: trigger-dv-man

  - name: tri-deploy-1
    type: tripubDeploy
    options:
      deployMethod: blueGreen
    steps:
      - GET: tri-man
      - GET: tri-man-2
      - GET: tri-cluster
