jobs:
  - name: gke-man
    type: manifest
    steps:
      - GET: gke-nginx
      - GET: trigger-dv-man

  - name: gke-deploy
    type: gkeDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: gke-man
      - GET: gke-cluster
