jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-1-1
        
  - name: runSh-job
    type: runSh
    steps:
      - IN: gitRepo-resource
        showBuildStatus: true
      - IN: rituraj-1-1
      - TASK:
        - script: echo 'start runSh hello'
        - script: printenv
    on_success:
      - script: echo "Hello from on_success"
      - NOTIFY: slack
      #- NOTIFY: slack

    on_failure:
      - script: echo "Hello from on_failure"
      - script: echo ":("
      - NOTIFY: email
      - NOTIFY: slack

    always:
      - script: echo "Hello from always"
      #- script: echo ":|"
      #- NOTIFY: email
      - NOTIFY: slack
        
