jobs:
  - name: beta-boxMan
    type: manifest
    steps:
      - GET: box-sn
      - GET: trigger-dv-man
      - TASK: managed

  # - name: b-ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: upgrade
  #   steps:
  #     - GET: b-box-man
  #     - GET: ecs-cluster

  # - name: b-tri-deploy
  #   type: tripubDeploy
  #   options:
  #     deployMethod: upgrade
  #   steps:
  #     - GET: b-box-man
  #     - GET: tri-cluster

  - name: beta-gkeDeploy
    type: gkeDeploy
    steps:
      - GET: beta-Man
      - GET: gkeCluster
      - TASK: managed
        deployMethod: blueGreen

  # - name: b-ddc-deploy
  #   type: ddcDeploy
  #   steps:
  #     - GET: b-box-man
  #     - GET: ddc-cluster

  # - name: b-dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - GET: b-box-man
  #     - GET: dcl-cluster
