jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-1-1
        
  - name: runSh-job
    type: runSh
    steps:
      - IN: rituraj-1-1
      - IN: gitRepo-resource
      - TASK:
        - script: echo 'start runSh hello new'
      - OUT: gitRepo-resource
        replicate: sample_php_ciRepo
      
        
