jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: app_image

  - name: myRunShJob
    type: runSh
    steps:
      - IN: aws_iam_int
      - TASK:
        - script: echo 'start runSh hello'

  - name: app_deploy_job
    type: deploy
    steps:
      - IN: rituraj-1-1
      - IN: op_cluster
