jobs:           
  - name: drydockTest
    type: runSh
    steps:
      - IN: test-gcloud-cli
      - TASK:
          name: should-list-gcloud-instances
          script:
            - docker run "drydock/c7all:master" "/c7all/services/service_test.sh"
