jobs:
  - name: beta-boxMan-1
    type: manifest
    steps:
      - IN: box-sn
      - IN: trigger-dv-man
      - TASK: managed

  - name: beta-boxMan-2
    type: manifest
    steps:
      - IN: box-nginx
      - IN: trigger-dv-man
      - TASK: managed

  # - name: b-ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: upgrade
  #   steps:
  #     - IN: b-box-man
  #     - IN: ecs-cluster

  # - name: b-tri-deploy
  #   type: tripubDeploy
  #   steps:
  #     - IN: beta-boxMan-1
  #     - IN: beta-boxMan-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: b-tri-deploy-bg
  #   type: tripubDeploy
  #   steps:
  #     - IN: beta-boxMan-1
  #     - IN: beta-boxMan-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: beta-gkeDeploy
  #   type: gkeDeploy
  #   steps:
  #     - IN: beta-boxMan
  #     - IN: gkeCluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: b-ddc-deploy
  #   type: ddcDeploy
  #   steps:
  #     - IN: b-box-man
  #     - IN: ddc-cluster

  - name: b-dcl-deploy
    type: dclDeploy
    steps:
      - IN: beta-boxMan-1
      - IN: beta-boxMan-2
      - IN: dcl-cluster
      - TASK: managed
