jobs:
  - name: beta-box-man
    type: manifest
    steps:
      - GET: box-sn
      - GET: box-nginx
      - GET: trigger-dv-man

  # - name: b-ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: upgrade
  #   steps:
  #     - GET: b-box-man
  #     - GET: ecs-cluster

  # - name: b-tri-deploy
  #   type: tripubDeploy
  #   options:
  #     deployMethod: upgrade
  #   steps:
  #     - GET: b-box-man
  #     - GET: tri-cluster

  - name: beta-gke-deploy
    type: gkeDeploy
    options:
      deployMethod: blueGreen
    steps:
      - GET: beta-box-man
      - GET: gke-cluster

  # - name: b-ddc-deploy
  #   type: ddcDeploy
  #   steps:
  #     - GET: b-box-man
  #     - GET: ddc-cluster

  # - name: b-dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - GET: b-box-man
  #     - GET: dcl-cluster
