jobs:
  - name: tri-man-2
    type: manifest
    steps:
      - IN: tri-nginx
      #- IN: trigger-dv-man

  - name: tri-deploy-11
    type: deploy
    TASK: managed
    deployMethod: blueGreen
    steps:
      - IN: tri-man-2
      - IN: tri-cluster
