jobs:           
  - name: x86-64-ubuntu-14-04-container-gcloud-cli-new-td
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: true
    flags:
      - x86-64
      - ubuntu-16-04
    steps:
      - IN: test-gcloud-cli
      - TASK:
          name: should-list-gcloud-instances
          script:
            - gcloud compute instances list
            - echo "hello"
            - echo "$TESTGCLOUDCLI_INTEGRATION_CREDENTIALFILE_PATH"
            
