jobs:
  - name: tri-man
    type: manifest
    steps:
      - GET: tri-nginx
      - GET: trigger-dv-man

  - name: tri-deploy
    type: tripubDeploy
    options:
      deployMethod: upgrade
    steps:
      - GET: tri-man
      - GET: tri-cluster
