jobs:
  - name: jD-1
    type: manifest
    steps:
      - IN: box-sn
        pull: false
          applyTo:
            - box-sn
      - TASK: managed
      - IN: trigger-dv-man
    on_success:
      - echo 'this is on_success step of dv-man of type manifest'
    on_failure:
      - echo 'this is on_failure step of dv-man of type manifest'

  - name: jatin-2
    type: manifest
    steps:
      - IN: box-sn
      - IN: trigger-dv-man
      - TASK: managed

  # - name: ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - IN: jatin-1
  #     - IN: jatin-2
  #     - IN: ecs-cluster

  - name: tri-deploy
    type: tripubDeploy
    steps:
      - IN: jatin-2
      - IN: gke-cluster-1
      - TASK: managed
        deployMethod: blueGreen

  # - name: tri-deploy-1
  #   type: tripubDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  - name: gkeDeploy
    type: gkeDeploy
    steps:
      - IN: jD-1
      - IN: gke-cluster-1
      - TASK: managed
        deployMethod: blueGreen

  # - name: ddc-deploy
  #   type: ddcDeploy
  #   steps:
  #     - IN: box-man-1
  #     - IN: ddc-cluster

  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: dcl-cluster
  #     - TASK: managed
