jobs:
  - name: x86-64-centos_7-container-shipctl
    type: runSh
    runtime:
      architecture: x86_64
      os: CentOS_7
      container: false
    flags:
      - x86-64
      - centos_7
    steps:
      #- IN: x86-64-trigger
      #- IN: ubuntu-16-04-trigger
      - TASK:
          name: shipctl-should-work
          script:
            - export OS_VERSION=$(rpm --eval '%{centos_ver}')
            - test "$OS_VERSION" == "7"
            - shipctl retry echo "it works"
