jobs:
  - name: x86-64-c7-drydock-c7odall
    type: runSh
    allowPublicAccess: true
    runtime:
      nodePool: custom__x86_64__Ubuntu_16_04
      container: true
    flags:
      - drydock
    steps:
      - TASK:
          name: check-java-4.8.7
          runtime:
            options:
              imageName: "drydock/c7javall"
              imageTag: master
          script:
            - shipctl jdk set openjdk8
