jobs:
  - name: manifest-job
    type: manifest
    steps:
      - IN: box-nginx-1
      
  - name: release-job-to-test-job-with-large-names-and-so-on
    type: release
    bump: final
    steps:
      - IN: manifest-job
      - IN: version-resource
