jobs:
      
  - name: rituraj-1-2-1-r
    type: manifest
    steps:
      - OUT: box-nginx-2-r
      - IN: docker-opts-r
 
  - name: sn-try-sh-r
    type: runSh
    steps:
      - OUT: box-nginx-2-r
      #- IN: rituraj-1-2-1
      - TASK:
          - script: echo "hello world"
          - script: sleep 1m
 
  - name: runcli1-r
    type: runCLI
    on_success:
      - hello
    steps:
      #- IN: myGitRepo
      - IN: rituraj-1-2-1-r
      - TASK:
        - script: printenv
        - script: sleep 1m

  # - name: sample-kube-ug-RC
  #   type: deploy
  #   steps:
  #     - IN: rituraj-1-2-1
  #     - IN: kube-deploy
  #     - TASK: managed
  #       deployMethod: upgrade
       
  - name: sample-kube-deploy1-8-r
    type: deploy
    steps:
      - IN: rituraj-1-2-1-r
      - IN: kube-deploy-r
      - TASK: managed-r
        deployMethod: upgrade

  - name: my-provision                                                   #required
    type: provision                                                  #required
    steps:
      - IN: kube-locad-balancer                 #required
      #- IN: <additional resource to be provisioned>                  #optional
        
  # - name: sample-kube-replace-RC
  #   type: deploy
  #   steps:
  #     - IN: rituraj-1-2-1
  #     - IN: kube-deploy
  #     - TASK: managed
  #       deployMethod: replace
  
  # - name: rituraj-release1-test
  #   type: release
  #   steps:
  #     - IN: real-version2
  #     - IN: rituraj-1-2-secure-1
  #     - IN: tr1

  # - name: ecs-deploy-rr
  #   type: deploy
  #   steps:
  #     - IN: rituraj-release1-test
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen
        
  
  # - name: real-ecsdeploy2
  #   type: deploy
  #   steps:
  #     - IN: rituraj-release1-test
  #     - IN: ecs-cluster

  # - name: ecs-deploy-bg
  #   type: ecsDeploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: ddc-cluster-deploy
  #   type: deploy
  #   on_start:
  #     - NOTIFY: slackNotification
  #   on_success:
  #     - NOTIFY: slackNotification
  #   steps:
  #     - IN: rituraj-2-1-param
  #     - IN: ddc-cluster
  #     - IN: rr-params
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: aws-deploy-13
  #   type: deploy
  #   steps:
  #     - IN: rituraj-2-1-param
  #     - IN: aws-cluster-11
  #     - IN: docker-opts
  #     - IN: tr1
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: gkeDeploy
  #   type: deploy
  #   steps:
  #     - IN: rituraj-2-2
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: gkeDeploy-bg
  #   type: deploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: ddc-deploy
  #   type: deploy
  #   steps:
  #     - IN: rituraj-2-1
  #     - IN: ddc-cluster

  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: dcl-cluster
  #     - TASK: managed
