jobs:
  - name: azureRunSHJob
    type: runSh
    steps:
      - IN: azureKeysIntResource
      - IN: azureCliConfig
      - TASK:
        - script: echo 'start runSh hello'
        #- script: printenv
        - script: echo 'Done!'
