jobs:
  - name: x86-64-ubuntu-14-04-container-artifactory-cli_new
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_14.04
      container: true
    flags:
      - x86-64
      - ubuntu-14-04
    steps:
      - IN: test-artifactory-cli_new
      - TASK:
          name: should-upload-file
          script:
            - export IMG=$(docker inspect --format='{{.Config.Image}}' reqExec.$BUILD_JOB_ID.0)
            - test "$IMG" == "drydock/microbase:master"
            - echo "build number is $BUILD_NUMBER" > myfile.$BUILD_NUMBER.txt
            - jfrog rt u myfile.$BUILD_NUMBER.txt generic-local/myfile.$BUILD_NUMBER.txt
