jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-1-1
        
  - name: runSh-job-array
    type: runSh
    steps:
      - IN: gitRepo-resource
        showBuildStatus: true
      - IN: rituraj-1-1
      - TASK:
        - script: echo 'start runSh hello'
        - script: printenv
    on_success:
      - script: echo "Hello from on_success array"
    #on_success:
      #script:
        #- echo "SUCCESS object"
    on_failure:
      - script: echo "Hello from on_failure"
      - script: echo ":("
    always:
      - script: echo "Hello from always"
      - script: echo ":|"
      
  - name: runSh-job-obj
    type: runSh
    steps:
      - IN: gitRepo-resource
        showBuildStatus: true
      - IN: rituraj-1-1
      - TASK:
        - script: echo 'start runSh hello 2'
        - script: printenv
     on_success:
      script:
        - echo "hello SUCCESS"
        - echo ":)"
    on_failure:
      script:
        - echo "hello FAILURE"
        - echo ":("
    always:
      script:
        - echo "hello ALWAYS"
        - echo ":|"
        
