jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-1-1-1
      #- IN: runcli1
    flags:
      - flg1

  # - name: docker-opts-1
  #   type: manifest
  #   steps:
  #     - IN: box-nginx-1-1
      
  # - name: rituraj-1-2
  #   type: manifest
  #   steps:
  #     - IN: box-nginx-2
  - name: sample_nodejs_runCI
    type: runCI
    steps:
      - OUT: box-nginx-1-1-1
      
  - name: myRunCLIJob
    type: runCLI
    steps:
      - IN: awsCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: which shippable_replace
        - script: echo 'this runCli job name is -> ${JOB_NAME}' > myJob.txt
        - script: cat myJob.txt
        - script: echo 'now doing shippable_replace'
        - script: shippable_replace myJob.txt
        - script: cat myJob.txt
        - script: aws ec2 describe-instances
        - script: echo 'hello runCli'

  - name: myRunShJob
    type: runSh
    steps:
      - IN: awsCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: which shippable_replace
        - script: cat `which shippable_replace`
        - script: echo 'this job name is -> ${JOB_NAME}' > myJob.txt
        - script: cat myJob.txt
        - script: echo 'now doing shippable_replace'
        - script: shippable_replace myJob.txt
        - script: cat myJob.txt
        - script: aws ec2 describe-instances
        - script: echo 'hello'

  - name: digiRunCLIJob
    type: runCLI
    steps:
      - IN: digiCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: doctl compute droplet list
        - script: echo 'hello runCli'

  - name: digiRunShJob
    type: runSh
    steps:
      - IN: digiCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: doctl compute droplet list
        - script: echo 'hello'

  - name: dockerRunCLIJob
    type: runCLI
    steps:
      - IN: dockerCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: docker pull riturajcse/rituexm
        - script: echo 'hello runCli'

  - name: dockerRunShJob
    type: runSh
    steps:
      - IN: dockerCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: docker pull riturajcse/rituexm
        - script: echo 'hello'

  - name: quayRunCLIJob
    type: runCLI
    steps:
      - IN: quayCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: docker pull quay.io/shippablequay/sample_node_01
        - script: echo 'hello runCli'

  - name: quayRunShJob
    type: runSh
    steps:
      - IN: quayCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: docker pull quay.io/shippablequay/sample_node_01
        - script: echo 'hello'

  - name: ecsRunCLIJob
    type: runCLI
    steps:
      - IN: ecrCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: docker pull 554282422391.dkr.ecr.us-west-2.amazonaws.com/sample_test:latest
        - script: echo 'hello runCli'

  - name: ecsRunShJob
    type: runSh
    steps:
      - IN: ecrCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: docker pull 554282422391.dkr.ecr.us-west-2.amazonaws.com/sample_test:latest
        - script: echo 'hello'

  - name: kubeRunCLIJob
    type: runCLI
    steps:
      - IN: kubeCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: kubectl get deployments
        - script: echo 'hello runCli'

  - name: kubeRunShJob
    type: runSh
    steps:
      - IN: kubeCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: kubectl get deployments
        - script: echo 'hello'

  - name: gclRunCLIJob
    type: runCLI
    steps:
      - IN: gclCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: gcloud compute instances list
        - script: echo 'hello runCli'

  - name: gclRunShJob
    type: runSh
    steps:
      - IN: gclCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: gcloud compute instances list
        - script: echo 'hello'

  - name: gcrRunCLIJob
    type: runCLI
    steps:
      - IN: gcrCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: gcloud docker -- pull gcr.io/vidya-project/ci-push-gcr:master.1
        - script: echo 'hello runCli'

  - name: gcrRunShJob
    type: runSh
    steps:
      - IN: gcrCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: gcloud docker -- pull gcr.io/vidya-project/ci-push-gcr:master.1
        - script: echo 'hello'

  - name: gkeRunCLIJob
    type: runCLI
    steps:
      - IN: gkeCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: gcloud container clusters list
        - script: echo 'hello runCli'

  - name: gkeRunShJob
    type: runSh
    steps:
      - IN: gkeCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: gcloud container clusters list
        - script: echo 'hello'
        
  - name: artifactRunCLIJob
    type: runCLI
    steps:
      - IN: artifactCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runCli hello'
        - script: docker pull rituraj-docker.jfrog.io/myimg:latest
        - script: echo 'hello runCli'

  - name: artifactRunSHJob
    type: runSh
    steps:
      - IN: artifactCLIConfig
      - IN: tr1
      - TASK:
        - script: echo 'start runSh hello'
        - script: docker pull rituraj-docker.jfrog.io/myimg:latest
        - script: echo 'hello'
  
 # at least one IN or OUT required

  # - name: runCli_job_for_testing
  #   type: runCLI
  #   steps:
  #     - IN: box-nginx-1-1
  #     - IN: box-nginx-1-2
  #     - IN: box-nginx-1-3
  #     - IN: box-nginx-1-4
  #     - IN: box-nginx-1-5
  #     - IN: box-nginx-1-6
  #     - IN: box-nginx-1-7
  #     - IN: box-nginx-1-8
  #     - IN: box-nginx-1-9
  #     - IN: box-nginx-1-10
  #     - IN: box-nginx-1-11
  #     - IN: box-nginx-1-12
  #     - IN: box-nginx-1-13
  #     - IN: box-nginx-1-14
  #     - IN: box-nginx-1-15
  #     - IN: box-nginx-1-16
  #     - IN: box-nginx-1-17
  #     - IN: box-nginx-1-18
  #     - IN: box-nginx-1-19
  #     - IN: box-nginx-1-20
  #     - TASK: 
  #       - script: printenv
 
      
  # - name: rituraj-release1-test
  #   type: release
  #   steps:
  #     - IN: real-version2
  #     - IN: rituraj-1-2-secure-1
  #     - IN: tr1

  # - name: ecs-deploy-rr
  #   type: deploy
  #   steps:
  #     - IN: rituraj-release1-test
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen
        
  
  # - name: real-ecsdeploy2
  #   type: deploy
  #   steps:
  #     - IN: rituraj-release1-test
  #     - IN: ecs-cluster

  # - name: ecs-deploy-bg
  #   type: ecsDeploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: ddc-cluster-deploy
  #   type: deploy
  #   on_start:
  #     - NOTIFY: slackNotification
  #   on_success:
  #     - NOTIFY: slackNotification
  #   steps:
  #     - IN: rituraj-2-1-param
  #     - IN: ddc-cluster
  #     - IN: rr-params
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: aws-deploy-13
  #   type: deploy
  #   steps:
  #     - IN: rituraj-2-1-param
  #     - IN: aws-cluster-11
  #     - IN: docker-opts
  #     - IN: tr1
  #     - TASK: managed
  #       deployMethod: upgrade


  # - name: gkeDeploy
  #   type: deploy
  #   steps:
  #     - IN: rituraj-2-2
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: gkeDeploy-bg
  #   type: deploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: ddc-deploy
  #   type: deploy
  #   steps:
  #     - IN: rituraj-2-1
  #     - IN: ddc-cluster

  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: dcl-cluster
  #     - TASK: managed
