jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-1-1

  - name: myRunShJob
    type: runSh
    steps:
      - IN: kube_integration_resource_new
      - TASK:
        - script: echo 'start runSh hello'
        - script: printenv

  - name: app_deploy_job_generic
    type: deploy
    steps:
      - IN: rituraj-1-1
      - IN: my_kube_cluster
      - IN: my_key_integration
      
  - name: app_deploy_job_old_bash
    type: deploy
    steps:
      - IN: rituraj-1-1
      - IN: my_kube_cluster_old-1-bash
