jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-1-1-100
      #- IN: runcli1
    flags:
      - flg1newfla1
     
      
  - name: rituraj-1-1-786-9098991200
    type: manifest
    steps:
      - IN: box-nginx-1-1
      #- IN: runcli1
    flags:
      - flg1
      
  - name: this-is-a-new-job
    type: manifest
    steps:
      - IN: box-nginx-1-1-1
      #- IN: runcli1
    flags:
      - flg143
      
  - name: this-is-a-new-job-tdoay1234
    type: manifest
    steps:
      - IN: box-nginx-1-1-1
      #- IN: runcli1
    flags:
      - flg143
      
  - name: new-job
    type: manifest
    steps:
      - IN: box-nginx-1-1-1
      #- IN: runcli1
    flags:
      - newglag
      
  - name: new-job-34
    type: manifest
    steps:
      - IN: box-nginx-1-1-1
      #- IN: runcli1
    flags:
      - newglag

  # - name: docker-opts-1
  #   type: manifest
  #   steps:
  #     - IN: box-nginx-1-1
      
  # - name: rituraj-1-2
  #   type: manifest
  #   steps:
  #     - IN: box-nginx-2
  #- name: sample_nodejs_runCI
   # type: runCI
    #steps:
     # - OUT: box-nginx-1-1-1
      
  - name: sample_nodejs_runCI
    type: runCI
    steps:
      - OUT: box-nginx-1-1-1
    flags:
      - flgCI1210RR321
      
  - name: jfrog-manifest
    type: manifest
    steps:
      #- IN: nodecluster-params
      - IN: jfrog-appfile
     
  - name: jfrog-manifest-OLD
    type: manifest
    steps:
      #- IN: nodecluster-params
      - IN: jfrog-appfile-OLD
      
  - name: jfrog-deploy
    type: deploy
    steps:
      - IN: jfrog-manifest
      - IN: deploy-nodecluster
      - TASK:
        - script: echo "hello jfrog NEW"
        #- script: jfrog rt dl test-repository-local/package.json
        
  - name: jfrog-deploy-OLD
    type: deploy
    steps:
      - IN: jfrog-manifest-OLD
      - IN: deploy-nodecluster
      #- TASK:
        #- script: echo "hello jfrog OLD"
        #- script: jfrog rt dl test-repository-local/package.json

  - name: myJfrogRunShJob
    type: runSh
    on_start:
      - NOTIFY: slackNotification
    on_success:
      - NOTIFY: slackNotification
    steps:
      - IN: jfrog-appfile
      #- IN: jFrog-cliconfig
      - IN: jfrogintnew
      #- IN:tr1
      - TASK:
        - script: echo 'start runSh hello jfrog new'
        - script: printenv
        - script: jfrog rt config --url $JFROGINTOLD_INTEGRATION_URL --password $JFROGINTOLD_INTEGRATION_PASSWORD --user $JFROGINTOLD_INTEGRATION_USERNAME
        - script: jfrog rt dl test-repository-local/shippable.yml
        - script: cp shippable.yml newPackage.$BUILD_NUMBER.shippable.yml
        - script: ls -al
        - script: jfrog rt u newPackage.$BUILD_NUMBER.shippable.yml
        
  - name: myJfrogRunShJob-OLD
    type: runSh
    on_start:
      - NOTIFY: slackNotification
    on_success:
      - NOTIFY: slackNotification
    steps:
      #- IN: jfrog-appfile-OLD
      - IN: jfrogintold
      #- IN:tr1
      - TASK:
        - script: echo 'start runSh hello jfrogOLD printenv'
        - script: printenv
        - script: jfrog rt config --url $JFROGINTOLD_INTEGRATION_URL --password $JFROGINTOLD_INTEGRATION_PASSWORD --user $JFROGINTOLD_INTEGRATION_USERNAME
        - script: jfrog rt dl test-repository-local/shippable.yml
        - script: cp shippable.yml newYmlTF.$BUILD_NUMBER.shippable.yml
        - script: ls -al
        - script: jfrog rt u newYmlTF.$BUILD_NUMBER.shippable.yml test-repository-local
        

  
 # at least one IN or OUT required

  # - name: runCli_job_for_testing
  #   type: runCLI
  #   steps:
  #     - IN: box-nginx-1-1
  #     - IN: box-nginx-1-2
  #     - IN: box-nginx-1-3
  #     - IN: box-nginx-1-4
  #     - IN: box-nginx-1-5
  #     - IN: box-nginx-1-6
  #     - IN: box-nginx-1-7
  #     - IN: box-nginx-1-8
  #     - IN: box-nginx-1-9
  #     - IN: box-nginx-1-10
  #     - IN: box-nginx-1-11
  #     - IN: box-nginx-1-12
  #     - IN: box-nginx-1-13
  #     - IN: box-nginx-1-14
  #     - IN: box-nginx-1-15
  #     - IN: box-nginx-1-16
  #     - IN: box-nginx-1-17
  #     - IN: box-nginx-1-18
  #     - IN: box-nginx-1-19
  #     - IN: box-nginx-1-20
  #     - TASK: 
  #       - script: printenv
 
      
  # - name: rituraj-release1-test
  #   type: release
  #   steps:
  #     - IN: real-version2
  #     - IN: rituraj-1-2-secure-1
  #     - IN: tr1

  # - name: ecs-deploy-rr
  #   type: deploy
  #   steps:
  #     - IN: rituraj-release1-test
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen
        
  
  # - name: real-ecsdeploy2
  #   type: deploy
  #   steps:
  #     - IN: rituraj-release1-test
  #     - IN: ecs-cluster

  # - name: ecs-deploy-bg
  #   type: ecsDeploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: ddc-cluster-deploy
  #   type: deploy
  #   on_start:
  #     - NOTIFY: slackNotification
  #   on_success:
  #     - NOTIFY: slackNotification
  #   steps:
  #     - IN: rituraj-2-1-param
  #     - IN: ddc-cluster
  #     - IN: rr-params
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: aws-deploy-13
  #   type: deploy
  #   steps:
  #     - IN: rituraj-2-1-param
  #     - IN: aws-cluster-11
  #     - IN: docker-opts
  #     - IN: tr1
  #     - TASK: managed
  #       deployMethod: upgrade


  # - name: gkeDeploy
  #   type: deploy
  #   steps:
  #     - IN: rituraj-2-2
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: gkeDeploy-bg
  #   type: deploy
  #   steps:
  #     - IN: jatin-2
  #     - IN: gke-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: ddc-deploy
  #   type: deploy
  #   steps:
  #     - IN: rituraj-2-1
  #     - IN: ddc-cluster

  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: dcl-cluster
  #     - TASK: managed
