jobs:
  - name: x86-64-ubuntu-container-shipctl
    type: runSh
    runtime:
      architecture: x86_64
      os: Ubuntu_16.04
      container: true
    flags:
      - x86-64
      - ubuntu16
    steps:
      - TASK:
          name: shipctl-should-work
          script:
            - echo "hello"
            - echo "hello all"
            - shipctl retry echo "it works"
    on_success:
      - script: echo "Hello from on_success"
      - script: echo ":)"

    on_failure:
      - script: echo "Hello from on_failure"
      - script: echo ":("

    always:
      - script: echo "Hello from always"
      - script: echo ":|"
