jobs:
  - name: beta-boxMan-b1
    type: manifest
    steps:
      - IN: box-nginx-b
      - IN: trigger-dv-man

  - name: beta-boxMan-b2
    type: manifest
    steps:
      - IN: box-sn-b
      - IN: trigger-dv-man

  # - name: b-ecs-deploy
  #   type: ecsDeploy
  #   steps:
  #     - IN: beta-boxMan-2
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: b-ecs-deploy
  #   type: ecsDeploy
  #   steps:
  #     - IN: beta-boxMan-1
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: b-tri-deploy-1
  #   type: tripubDeploy
  #   steps:
  #     - IN: beta-boxMan-1
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: b-tri-deploy-2
  #   type: tripubDeploy
  #   steps:
  #     - IN: beta-boxMan-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: b-tri-deploy-bg
  #   type: tripubDeploy
  #   steps:
  #     - IN: beta-boxMan-1
  #     - IN: beta-boxMan-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  - name: beta-gkeDeploy-b1
    type: deploy
    steps:
      - IN: beta-boxMan-b1
      - IN: gkeCluster-b
      - TASK: managed
        deployMethod: blueGreen

  - name: beta-gkeDeploy-b2
    type: deploy
    steps:
      - IN: beta-boxMan-b2
      - IN: gkeCluster-b
      - TASK: managed
        deployMethod: upgrade

  # - name: b-ddc-deploy
  #   type: ddcDeploy
  #   steps:
  #     - IN: b-box-man
  #     - IN: ddc-cluster

  # - name: b-dcl-deploy-1
  #   type: dclDeploy
  #   steps:
  #     - IN: beta-boxMan-1-1
  #     - IN: beta-boxMan-2-1
  #     - IN: dcl-cluster-1
  #     - TASK: managed
