jobs:
  - name: x86-64-ubuntu-container-shipctl
    type: runSh
    steps:
      - TASK:
          name: shipctl-should-work
          script:
            - echo "hello"
            - echo "hello all"
            - shipctl retry echo "it works"
