jobs:
  - name: jD-1
    type: manifest
    steps:
      - IN: box-sn
      - IN: trigger-dv-man
      - TASK: managed

  - name: jatin-2
    type: manifest
    steps:
      - IN: box-nginx
      - IN: trigger-dv-man
      - TASK: managed

  # - name: ecs-deploy
  #   type: ecsDeploy
  #   options:
  #     deployMethod: blueGreen
  #   steps:
  #     - GET: jatin-1
  #     - GET: jatin-2
  #     - GET: ecs-cluster

  # - name: tri-deploy
  #   type: tripubDeploy
  #   steps:
  #     - GET: jD-1
  #     - GET: jatin-2
  #     - GET: tri-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: tri-deploy-1
  #   type: tripubDeploy
  #   steps:
  #     - GET: jD-1
  #     - GET: jatin-2
  #     - GET: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  - name: gkeDeploy
    type: gkeDeploy
    steps:
      - GET: jD-1
      - GET: gke-cluster
      - TASK: managed
        deployMethod: upgrade

  # - name: ddc-deploy
  #   type: ddcDeploy
  #   steps:
  #     - GET: box-man-1
  #     - GET: ddc-cluster

  # - name: dcl-deploy
  #   type: dclDeploy
  #   steps:
  #     - IN: jD-1
  #     - IN: jatin-2
  #     - IN: dcl-cluster
  #     - TASK: managed
