jobs:
  - name: beta-boxMan-1
    type: manifest
    steps:
      - IN: box-nginx-1
      - IN: trigger-dv-man
      - TASK: managed

  # - name: beta-boxMan-2
  #   type: manifest
  #   steps:
  #     - IN: box-sn-1
  #     - IN: trigger-dv-man
  #     - TASK: managed

  # - name: b-ecs-deploy
  #   type: ecsDeploy
  #   steps:
  #     - IN: beta-boxMan-2
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  # - name: b-ecs-deploy
  #   type: ecsDeploy
  #   steps:
  #     - IN: beta-boxMan-1
  #     - IN: ecs-cluster
  #     - TASK: managed
  #       deployMethod: upgrade

  - name: b-tri-deploy
    type: tripubDeploy
    steps:
      - IN: beta-boxMan-1
      - IN: tri-cluster
      - TASK: managed
        deployMethod: upgrade

  # - name: b-tri-deploy-bg
  #   type: tripubDeploy
  #   steps:
  #     - IN: beta-boxMan-1
  #     - IN: beta-boxMan-2
  #     - IN: tri-cluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: beta-gkeDeploy
  #   type: gkeDeploy
  #   steps:
  #     - IN: beta-boxMan
  #     - IN: gkeCluster
  #     - TASK: managed
  #       deployMethod: blueGreen

  # - name: b-ddc-deploy
  #   type: ddcDeploy
  #   steps:
  #     - IN: b-box-man
  #     - IN: ddc-cluster

  # - name: b-dcl-deploy-1
  #   type: dclDeploy
  #   steps:
  #     - IN: beta-boxMan-1-1
  #     - IN: beta-boxMan-2-1
  #     - IN: dcl-cluster-1
  #     - TASK: managed
