jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-1-1
        
  - name: sample_php_runCI
    type: runCI
    steps:
      - OUT: gitRepo-resource
        replicate: sample_php_ciRepo
      
        
