jobs:
  - name: rituraj-1-1
    type: manifest
    steps:
      - IN: box-nginx-1-1-1

  - name: myRunShJob
    type: runSh
    steps:
      - IN: aws_iam_int
      - TASK:
        - script: echo 'start runSh hello'
        - script: printenv
        - script: echo 'Done!'
