jobs:
  - name: x86-64-ubuntu-container-shipctl
    type: runSh
    steps:
      - TASK:
        - script: echo "hello"
        - script: echo "hello all"

  - name: x86-64-ubuntu-container-shipctl-2
    type: runSh
    steps:
      - TASK:
        - script: echo "hello"
        - script: echo "hello all"

